// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/monitor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MonitorService_SendMetrics_FullMethodName       = "/monitor.MonitorService/SendMetrics"
	MonitorService_GetMetrics_FullMethodName        = "/monitor.MonitorService/GetMetrics"
	MonitorService_SaveMetrics_FullMethodName       = "/monitor.MonitorService/SaveMetrics"
	MonitorService_GetMetricsHistory_FullMethodName = "/monitor.MonitorService/GetMetricsHistory"
	MonitorService_GetMetricsStats_FullMethodName   = "/monitor.MonitorService/GetMetricsStats"
	MonitorService_DeleteMetrics_FullMethodName     = "/monitor.MonitorService/DeleteMetrics"
)

// MonitorServiceClient is the client API for MonitorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 监控数据服务
type MonitorServiceClient interface {
	// 发送监控数据
	SendMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricsData, MetricsResponse], error)
	// 获取监控数据
	GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricsData], error)
	// 保存指标数据
	SaveMetrics(ctx context.Context, in *SaveMetricsRequest, opts ...grpc.CallOption) (*SaveMetricsResponse, error)
	// 获取指标历史数据
	GetMetricsHistory(ctx context.Context, in *GetMetricsHistoryRequest, opts ...grpc.CallOption) (*GetMetricsHistoryResponse, error)
	// 获取指标统计信息
	GetMetricsStats(ctx context.Context, in *GetMetricsStatsRequest, opts ...grpc.CallOption) (*GetMetricsStatsResponse, error)
	// 删除指标数据
	DeleteMetrics(ctx context.Context, in *DeleteMetricsRequest, opts ...grpc.CallOption) (*DeleteMetricsResponse, error)
}

type monitorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitorServiceClient(cc grpc.ClientConnInterface) MonitorServiceClient {
	return &monitorServiceClient{cc}
}

func (c *monitorServiceClient) SendMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricsData, MetricsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MonitorService_ServiceDesc.Streams[0], MonitorService_SendMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MetricsData, MetricsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonitorService_SendMetricsClient = grpc.ClientStreamingClient[MetricsData, MetricsResponse]

func (c *monitorServiceClient) GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricsData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MonitorService_ServiceDesc.Streams[1], MonitorService_GetMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MetricsRequest, MetricsData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonitorService_GetMetricsClient = grpc.ServerStreamingClient[MetricsData]

func (c *monitorServiceClient) SaveMetrics(ctx context.Context, in *SaveMetricsRequest, opts ...grpc.CallOption) (*SaveMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveMetricsResponse)
	err := c.cc.Invoke(ctx, MonitorService_SaveMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetMetricsHistory(ctx context.Context, in *GetMetricsHistoryRequest, opts ...grpc.CallOption) (*GetMetricsHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsHistoryResponse)
	err := c.cc.Invoke(ctx, MonitorService_GetMetricsHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetMetricsStats(ctx context.Context, in *GetMetricsStatsRequest, opts ...grpc.CallOption) (*GetMetricsStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsStatsResponse)
	err := c.cc.Invoke(ctx, MonitorService_GetMetricsStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) DeleteMetrics(ctx context.Context, in *DeleteMetricsRequest, opts ...grpc.CallOption) (*DeleteMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMetricsResponse)
	err := c.cc.Invoke(ctx, MonitorService_DeleteMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorServiceServer is the server API for MonitorService service.
// All implementations must embed UnimplementedMonitorServiceServer
// for forward compatibility.
//
// 监控数据服务
type MonitorServiceServer interface {
	// 发送监控数据
	SendMetrics(grpc.ClientStreamingServer[MetricsData, MetricsResponse]) error
	// 获取监控数据
	GetMetrics(*MetricsRequest, grpc.ServerStreamingServer[MetricsData]) error
	// 保存指标数据
	SaveMetrics(context.Context, *SaveMetricsRequest) (*SaveMetricsResponse, error)
	// 获取指标历史数据
	GetMetricsHistory(context.Context, *GetMetricsHistoryRequest) (*GetMetricsHistoryResponse, error)
	// 获取指标统计信息
	GetMetricsStats(context.Context, *GetMetricsStatsRequest) (*GetMetricsStatsResponse, error)
	// 删除指标数据
	DeleteMetrics(context.Context, *DeleteMetricsRequest) (*DeleteMetricsResponse, error)
	mustEmbedUnimplementedMonitorServiceServer()
}

// UnimplementedMonitorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonitorServiceServer struct{}

func (UnimplementedMonitorServiceServer) SendMetrics(grpc.ClientStreamingServer[MetricsData, MetricsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SendMetrics not implemented")
}
func (UnimplementedMonitorServiceServer) GetMetrics(*MetricsRequest, grpc.ServerStreamingServer[MetricsData]) error {
	return status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedMonitorServiceServer) SaveMetrics(context.Context, *SaveMetricsRequest) (*SaveMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveMetrics not implemented")
}
func (UnimplementedMonitorServiceServer) GetMetricsHistory(context.Context, *GetMetricsHistoryRequest) (*GetMetricsHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetricsHistory not implemented")
}
func (UnimplementedMonitorServiceServer) GetMetricsStats(context.Context, *GetMetricsStatsRequest) (*GetMetricsStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetricsStats not implemented")
}
func (UnimplementedMonitorServiceServer) DeleteMetrics(context.Context, *DeleteMetricsRequest) (*DeleteMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMetrics not implemented")
}
func (UnimplementedMonitorServiceServer) mustEmbedUnimplementedMonitorServiceServer() {}
func (UnimplementedMonitorServiceServer) testEmbeddedByValue()                        {}

// UnsafeMonitorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitorServiceServer will
// result in compilation errors.
type UnsafeMonitorServiceServer interface {
	mustEmbedUnimplementedMonitorServiceServer()
}

func RegisterMonitorServiceServer(s grpc.ServiceRegistrar, srv MonitorServiceServer) {
	// If the following call pancis, it indicates UnimplementedMonitorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MonitorService_ServiceDesc, srv)
}

func _MonitorService_SendMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MonitorServiceServer).SendMetrics(&grpc.GenericServerStream[MetricsData, MetricsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonitorService_SendMetricsServer = grpc.ClientStreamingServer[MetricsData, MetricsResponse]

func _MonitorService_GetMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MonitorServiceServer).GetMetrics(m, &grpc.GenericServerStream[MetricsRequest, MetricsData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonitorService_GetMetricsServer = grpc.ServerStreamingServer[MetricsData]

func _MonitorService_SaveMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).SaveMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_SaveMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).SaveMetrics(ctx, req.(*SaveMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetMetricsHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetMetricsHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetMetricsHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetMetricsHistory(ctx, req.(*GetMetricsHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetMetricsStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetMetricsStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetMetricsStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetMetricsStats(ctx, req.(*GetMetricsStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_DeleteMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).DeleteMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_DeleteMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).DeleteMetrics(ctx, req.(*DeleteMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MonitorService_ServiceDesc is the grpc.ServiceDesc for MonitorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonitorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.MonitorService",
	HandlerType: (*MonitorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveMetrics",
			Handler:    _MonitorService_SaveMetrics_Handler,
		},
		{
			MethodName: "GetMetricsHistory",
			Handler:    _MonitorService_GetMetricsHistory_Handler,
		},
		{
			MethodName: "GetMetricsStats",
			Handler:    _MonitorService_GetMetricsStats_Handler,
		},
		{
			MethodName: "DeleteMetrics",
			Handler:    _MonitorService_DeleteMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendMetrics",
			Handler:       _MonitorService_SendMetrics_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetMetrics",
			Handler:       _MonitorService_GetMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/monitor.proto",
}

const (
	RaftService_AppendEntries_FullMethodName = "/monitor.RaftService/AppendEntries"
	RaftService_RequestVote_FullMethodName   = "/monitor.RaftService/RequestVote"
)

// RaftServiceClient is the client API for RaftService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Raft服务
type RaftServiceClient interface {
	// 发送日志条目
	AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error)
	// 请求投票
	RequestVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error)
}

type raftServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftServiceClient(cc grpc.ClientConnInterface) RaftServiceClient {
	return &raftServiceClient{cc}
}

func (c *raftServiceClient) AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendEntriesResponse)
	err := c.cc.Invoke(ctx, RaftService_AppendEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftServiceClient) RequestVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoteResponse)
	err := c.cc.Invoke(ctx, RaftService_RequestVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftServiceServer is the server API for RaftService service.
// All implementations must embed UnimplementedRaftServiceServer
// for forward compatibility.
//
// Raft服务
type RaftServiceServer interface {
	// 发送日志条目
	AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error)
	// 请求投票
	RequestVote(context.Context, *VoteRequest) (*VoteResponse, error)
	mustEmbedUnimplementedRaftServiceServer()
}

// UnimplementedRaftServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaftServiceServer struct{}

func (UnimplementedRaftServiceServer) AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendEntries not implemented")
}
func (UnimplementedRaftServiceServer) RequestVote(context.Context, *VoteRequest) (*VoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVote not implemented")
}
func (UnimplementedRaftServiceServer) mustEmbedUnimplementedRaftServiceServer() {}
func (UnimplementedRaftServiceServer) testEmbeddedByValue()                     {}

// UnsafeRaftServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftServiceServer will
// result in compilation errors.
type UnsafeRaftServiceServer interface {
	mustEmbedUnimplementedRaftServiceServer()
}

func RegisterRaftServiceServer(s grpc.ServiceRegistrar, srv RaftServiceServer) {
	// If the following call pancis, it indicates UnimplementedRaftServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RaftService_ServiceDesc, srv)
}

func _RaftService_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServiceServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftService_AppendEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServiceServer).AppendEntries(ctx, req.(*AppendEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftService_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServiceServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftService_RequestVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServiceServer).RequestVote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RaftService_ServiceDesc is the grpc.ServiceDesc for RaftService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.RaftService",
	HandlerType: (*RaftServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntries",
			Handler:    _RaftService_AppendEntries_Handler,
		},
		{
			MethodName: "RequestVote",
			Handler:    _RaftService_RequestVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/monitor.proto",
}
