# 可视化分析端配置

# 服务器配置
server:
  host: "localhost"
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 30s

# 中转层配置
broker:
  endpoints:
    - "localhost:9093"
  timeout: 5s
  max_retry: 3

# WebSocket配置
websocket:
  enable: true
  path: "/ws"
  read_buffer_size: 1024
  write_buffer_size: 1024
  max_message_size: 524288  # 512KB
  ping_interval: 30s
  ping_timeout: 60s
  pong_timeout: 60s
  write_timeout: 10s
  buffer_size: 8192

# QUIC配置
quic:
  enable: true   # 启用QUIC支持
  port: 8081
  max_streams_per_conn: 100
  keep_alive_period: 30s
  max_idle_timeout: 60s
  buffer_size: 8192

# 认证配置
auth:
  jwt_secret: "your-secret-key-here"
  token_expiration: 15m
  refresh_token_expiration: 24h
  cookie_secure: false
  cookie_http_only: true
  cookie_name: "monitor_token"
  refresh_cookie_name: "monitor_refresh_token"

# Top-K配置
topk:
  size: 10
  ttl: 1h

# 缓存配置
cache:
  ttl: 5m
  cleanup_interval: 5m

# 日志配置
log:
  level: "info"
  format: "json"
  output: "logs/visualization.log" 